{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import FreeCAD\n",
    "import FreeCADGui\n",
    "import Part\n",
    "\n",
    "\n",
    "class Coupling:\n",
    "\n",
    "    part001 = None\n",
    "    body001 = None\n",
    "    sketch001body001 = None\n",
    "    pad001body001 = None\n",
    "    hole001body001 = None\n",
    "    local001part001 = None\n",
    "    sketch002body001 = None\n",
    "    pocket001body001 = None\n",
    "    sketch003body001 = None\n",
    "    pocket002body001 = None\n",
    "\n",
    "    def __init__(self):\n",
    "        self.document = FreeCAD.ActiveDocument\n",
    "        self.view = FreeCADGui.ActiveDocument.ActiveView\n",
    "\n",
    "        self.__part001('Part001Coupling')\n",
    "        self.__body001('Body001Coupling')\n",
    "        self.__sketch001body001('Sketch001Body001Coupling')\n",
    "        self.__pad001body001('Pad001Body001Coupling')\n",
    "        self.__hole001body001('Hole001Body001Coupling')\n",
    "        self.__local001part001('Local001Part001Coupling')\n",
    "        self.__sketch002body001('Sketch002Body001Coupling')\n",
    "        self.__pocket001body001('Pocket001Body001Coupling')\n",
    "        self.__sketch003body001('Sketch003Body001Coupling')\n",
    "        self.__pocket002body001('Pocket002Body001Coupling')\n",
    "\n",
    "        self.view.setActiveObject('part', None)\n",
    "        self.view.setActiveObject('pdbody', None)\n",
    "\n",
    "    def __part001(self, name):\n",
    "        if self.document.getObject(name):\n",
    "            self.document.getObject(name).removeObjectsFromDocument()\n",
    "            self.document.removeObject(name)\n",
    "            self.document.recompute()\n",
    "\n",
    "        self.part001 = self.document.addObject('App::Part', name)\n",
    "        self.view.setActiveObject('part', self.part001)\n",
    "        self.document.recompute()\n",
    "\n",
    "    def __body001(self, name):\n",
    "        self.body001 = self.part001.newObject('PartDesign::Body', name)\n",
    "        self.view.setActiveObject('pdbody', self.body001)\n",
    "        self.document.recompute()\n",
    "\n",
    "    def __sketch001body001(self, name):\n",
    "        self.sketch001body001 = self.body001.newObject('Sketcher::SketchObject', name)\n",
    "        self.sketch001body001.Support = self.body001.Origin.OriginFeatures[3]  # XY_Plane\n",
    "        self.sketch001body001.MapMode = 'FlatFace'\n",
    "        self.document.recompute()\n",
    "\n",
    "        self.sketch001body001.addGeometry([\n",
    "            Part.Circle(FreeCAD.Vector(0, 0, 0), FreeCAD.Vector(0, 0, 1), 5/2),  # 0\n",
    "            Part.Circle(FreeCAD.Vector(0, 0, 0), FreeCAD.Vector(0, 0, 1), 19/2),  # 1\n",
    "        ], False)\n",
    "        self.sketch001body001.Visibility = False\n",
    "        self.document.recompute()\n",
    "\n",
    "    def __pad001body001(self, name):\n",
    "        self.pad001body001 = self.body001.newObject('PartDesign::Pad', name)\n",
    "        self.pad001body001.Profile = self.sketch001body001\n",
    "        self.pad001body001.Midplane = True\n",
    "        self.pad001body001.Length = 24\n",
    "        self.document.recompute()\n",
    "\n",
    "    def __hole001body001(self, name):\n",
    "        self.hole001body001 = self.body001.newObject('PartDesign::Hole', name)\n",
    "        self.hole001body001.Profile = (self.pad001body001, ['Edge6', ])\n",
    "        self.hole001body001.Diameter = 8\n",
    "        self.hole001body001.Depth = 18\n",
    "        self.hole001body001.DrillPoint = 'Flat'\n",
    "        self.document.recompute()\n",
    "\n",
    "    # ISSUE: Links go out of the allowed scope.\n",
    "    def __local001part001(self, name):\n",
    "        self.local001part001 = self.part001.newObject('PartDesign::CoordinateSystem', name)\n",
    "        self.local001part001.Support = [(self.hole001body001, 'Edge7')]\n",
    "        self.local001part001.MapMode = 'InertialCS'\n",
    "        self.local001part001.AttachmentOffset = FreeCAD.Placement(FreeCAD.Vector(0, 0, 7.5), FreeCAD.Rotation(0, 0, 0))\n",
    "        self.local001part001.Visibility = False\n",
    "        self.document.recompute()\n",
    "\n",
    "    def __sketch002body001(self, name):\n",
    "        self.sketch002body001 = self.body001.newObject('Sketcher::SketchObject', name)\n",
    "        self.sketch002body001.Support = self.body001.Origin.OriginFeatures[5]  # YZ_Plane\n",
    "        self.sketch002body001.MapMode = 'FlatFace'\n",
    "        self.document.recompute()\n",
    "\n",
    "        self.sketch002body001.addGeometry([\n",
    "            Part.Circle(FreeCAD.Vector(0, 8, 0), FreeCAD.Vector(0, 0, 1), 4/2),  # 0\n",
    "            Part.Circle(FreeCAD.Vector(0, -8, 0), FreeCAD.Vector(0, 0, 1), 4/2),  # 1\n",
    "        ], False)\n",
    "        self.sketch002body001.Visibility = False\n",
    "        self.document.recompute()\n",
    "\n",
    "    def __pocket001body001(self, name):\n",
    "        self.pocket001body001 = self.body001.newObject('PartDesign::Pocket', name)\n",
    "        self.pocket001body001.Profile = self.sketch002body001\n",
    "        self.pocket001body001.Reversed = True\n",
    "        self.pocket001body001.Type = 'ThroughAll'\n",
    "        self.document.recompute()\n",
    "\n",
    "    def __sketch003body001(self, name):\n",
    "        self.sketch003body001 = self.body001.newObject('Sketcher::SketchObject', name)\n",
    "        self.sketch003body001.Support = self.body001.Origin.OriginFeatures[4]  # XZ_Plane\n",
    "        self.sketch003body001.MapMode = 'FlatFace'\n",
    "        self.sketch003body001.Geometry = self.sketch002body001.Geometry\n",
    "        self.sketch003body001.Visibility = False\n",
    "        self.document.recompute()\n",
    "\n",
    "    def __pocket002body001(self, name):\n",
    "        self.pocket002body001 = self.body001.newObject('PartDesign::Pocket', name)\n",
    "        self.pocket002body001.Profile = self.sketch003body001\n",
    "        self.pocket002body001.Reversed = True\n",
    "        self.pocket002body001.Type = 'ThroughAll'\n",
    "        self.document.recompute()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "FreeCAD",
   "language": "",
   "name": "freecad"
  },
  "language_info": {
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
