{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 114,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Framework Document\n",
    "\n",
    "if 'Framework' in App.listDocuments():\n",
    "    App.closeDocument('Framework')\n",
    "\n",
    "App.newDocument('Framework')\n",
    "App.ActiveDocument.saveAs(\"./Framework/Framework.FCStd\")\n",
    "\n",
    "App.openDocument('./Sketches/Sketches.FCStd')\n",
    "\n",
    "App.setActiveDocument('Framework')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 115,
   "metadata": {},
   "outputs": [],
   "source": [
    "# PartDesign Workbench\n",
    "\n",
    "Gui.ActiveDocument.ActiveView.viewDefaultOrientation()\n",
    "Gui.ActiveDocument.ActiveView.setCameraType(\"Perspective\")\n",
    "Gui.activateWorkbench(\"PartDesignWorkbench\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Square Tube Profile Sketch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 116,
   "metadata": {},
   "outputs": [],
   "source": [
    "# SquareTubeProfileSketch\n",
    "\n",
    "if App.ActiveDocument.getObject('SquareTubeProfileSketch'):\n",
    "    App.ActiveDocument.removeObject('SquareTubeProfileSketch')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.addObject('App::Link', 'SquareTubeProfileSketch')\n",
    "App.ActiveDocument.getObject('SquareTubeProfileSketch').LinkedObject = App.getDocument('Sketches').getObject('SquareTubeProfileSketch')\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Square Tube X Axis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 117,
   "metadata": {},
   "outputs": [],
   "source": [
    "# SquareTubeXAxis\n",
    "\n",
    "if App.ActiveDocument.getObject('SquareTubeXAxis'):\n",
    "    App.ActiveDocument.getObject('SquareTubeXAxis').removeObjectsFromDocument()\n",
    "    App.ActiveDocument.removeObject('SquareTubeXAxis')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.addObject('PartDesign::Body', 'SquareTubeXAxis')\n",
    "App.ActiveDocument.getObject('SquareTubeXAxis').Label = 'Square Tube X Axis'\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "Gui.ActiveDocument.ActiveView.setActiveObject('pdbody', App.ActiveDocument.getObject('SquareTubeXAxis'))\n",
    "\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 118,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Binder001\n",
    "\n",
    "if App.ActiveDocument.getObject('Binder001'):\n",
    "    App.ActiveDocument.removeObject('Binder001')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeXAxis').newObject('PartDesign::SubShapeBinder', 'Binder001')\n",
    "App.ActiveDocument.getObject('Binder001').Support = [(App.ActiveDocument.getObject('SquareTubeProfileSketch'), ('',))]\n",
    "App.ActiveDocument.getObject('Binder001').Placement = App.Placement(App.Vector(0, 0, 0), App.Rotation(App.Vector(0, 0, 1), 90))\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeProfileSketch').Visibility = False\n",
    "\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 119,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Pad001\n",
    "\n",
    "if App.ActiveDocument.getObject('Pad001'):\n",
    "    App.ActiveDocument.removeObject('Pad001')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeXAxis').newObject('PartDesign::Pad', 'Pad001')\n",
    "App.ActiveDocument.getObject('Pad001').Profile = App.ActiveDocument.getObject('Binder001')\n",
    "App.ActiveDocument.getObject('Pad001').Length = 1500 - 2*40\n",
    "App.ActiveDocument.getObject('Pad001').Midplane = True\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('Binder001').Visibility = False\n",
    "\n",
    "Gui.ActiveDocument.ActiveView.setActiveObject('pdbody', None)\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 120,
   "metadata": {},
   "outputs": [],
   "source": [
    "App.ActiveDocument.getObject('SquareTubeXAxis').Visibility = False\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Square Tube Y Axis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 121,
   "metadata": {},
   "outputs": [],
   "source": [
    "# SquareTubeYAxis\n",
    "\n",
    "if App.ActiveDocument.getObject('SquareTubeYAxis'):\n",
    "    App.ActiveDocument.getObject('SquareTubeYAxis').removeObjectsFromDocument()\n",
    "    App.ActiveDocument.removeObject('SquareTubeYAxis')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.addObject('PartDesign::Body', 'SquareTubeYAxis')\n",
    "App.ActiveDocument.getObject('SquareTubeYAxis').Label = 'Square Tube Y Axis'\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "Gui.ActiveDocument.ActiveView.setActiveObject('pdbody', App.ActiveDocument.getObject('SquareTubeYAxis'))\n",
    "\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 122,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Binder002\n",
    "\n",
    "if App.ActiveDocument.getObject('Binder002'):\n",
    "    App.ActiveDocument.removeObject('Binder002')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeYAxis').newObject('PartDesign::SubShapeBinder', 'Binder002')\n",
    "App.ActiveDocument.getObject('Binder002').Support = [(App.ActiveDocument.getObject('SquareTubeProfileSketch'), ('',))]\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeProfileSketch').Visibility = False\n",
    "\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 123,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Pad002\n",
    "\n",
    "if App.ActiveDocument.getObject('Pad002'):\n",
    "    App.ActiveDocument.removeObject('Pad002')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeYAxis').newObject('PartDesign::Pad', 'Pad002')\n",
    "App.ActiveDocument.getObject('Pad002').Profile = App.ActiveDocument.getObject('Binder002')\n",
    "App.ActiveDocument.getObject('Pad002').Length = 1500 - 2*40\n",
    "App.ActiveDocument.getObject('Pad002').Midplane = True\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('Binder002').Visibility = False\n",
    "\n",
    "Gui.ActiveDocument.ActiveView.setActiveObject('pdbody', None)\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 124,
   "metadata": {},
   "outputs": [],
   "source": [
    "App.ActiveDocument.getObject('SquareTubeYAxis').Visibility = False\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Square Tube Z Axis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 125,
   "metadata": {},
   "outputs": [],
   "source": [
    "# SquareTubeZAxis\n",
    "\n",
    "if App.ActiveDocument.getObject('SquareTubeZAxis'):\n",
    "    App.ActiveDocument.getObject('SquareTubeZAxis').removeObjectsFromDocument()\n",
    "    App.ActiveDocument.removeObject('SquareTubeZAxis')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.addObject('PartDesign::Body', 'SquareTubeZAxis')\n",
    "App.ActiveDocument.getObject('SquareTubeZAxis').Label = 'Square Tube Z Axis'\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "Gui.ActiveDocument.ActiveView.setActiveObject('pdbody', App.ActiveDocument.getObject('SquareTubeZAxis'))\n",
    "\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 126,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Binder003\n",
    "\n",
    "if App.ActiveDocument.getObject('Binder003'):\n",
    "    App.ActiveDocument.removeObject('Binder003')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeZAxis').newObject('PartDesign::SubShapeBinder', 'Binder003')\n",
    "App.ActiveDocument.getObject('Binder003').Support = [(App.ActiveDocument.getObject('SquareTubeProfileSketch'), ('',))]\n",
    "App.ActiveDocument.getObject('Binder003').Placement = App.Placement(App.Vector(0, 0, 0), App.Rotation(App.Vector(1, 0, 0), -90))\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeProfileSketch').Visibility = False\n",
    "\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 127,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Pad003\n",
    "\n",
    "if App.ActiveDocument.getObject('Pad003'):\n",
    "    App.ActiveDocument.removeObject('Pad003')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeZAxis').newObject('PartDesign::Pad', 'Pad003')\n",
    "App.ActiveDocument.getObject('Pad003').Profile = App.ActiveDocument.getObject('Binder003')\n",
    "App.ActiveDocument.getObject('Pad003').Length = 1200\n",
    "App.ActiveDocument.getObject('Pad003').Midplane = True\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('Binder003').Visibility = False\n",
    "\n",
    "\n",
    "if App.ActiveDocument.getObject('Pad004'):\n",
    "    App.ActiveDocument.removeObject('Pad004')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeZAxis').newObject('PartDesign::Pad', 'Pad004')\n",
    "App.ActiveDocument.getObject('Pad004').Profile = (App.ActiveDocument.getObject('Pad003'), ['Face18', ])\n",
    "App.ActiveDocument.getObject('Pad004').Length = 40\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('Pad003').Visibility = False\n",
    "\n",
    "\n",
    "if App.ActiveDocument.getObject('Pad005'):\n",
    "    App.ActiveDocument.removeObject('Pad005')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeZAxis').newObject('PartDesign::Pad', 'Pad005')\n",
    "App.ActiveDocument.getObject('Pad005').Profile = (App.ActiveDocument.getObject('Pad004'), ['Face4', ])\n",
    "App.ActiveDocument.getObject('Pad005').Length = 40\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('Pad004').Visibility = False\n",
    "\n",
    "\n",
    "if App.ActiveDocument.getObject('Pad006'):\n",
    "    App.ActiveDocument.removeObject('Pad006')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeZAxis').newObject('PartDesign::Pad', 'Pad006')\n",
    "App.ActiveDocument.getObject('Pad006').Profile = (App.ActiveDocument.getObject('Pad005'), ['Face12', ])\n",
    "App.ActiveDocument.getObject('Pad006').Length = 400\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('Pad005').Visibility = False\n",
    "\n",
    "\n",
    "if App.ActiveDocument.getObject('Pad007'):\n",
    "    App.ActiveDocument.removeObject('Pad007')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('SquareTubeZAxis').newObject('PartDesign::Pad', 'Pad007')\n",
    "App.ActiveDocument.getObject('Pad007').Profile = (App.ActiveDocument.getObject('Pad006'), ['Face22', ])\n",
    "App.ActiveDocument.getObject('Pad007').Length = 40\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.getObject('Pad006').Visibility = False\n",
    "\n",
    "\n",
    "Gui.ActiveDocument.ActiveView.setActiveObject('pdbody', None)\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 128,
   "metadata": {},
   "outputs": [],
   "source": [
    "App.ActiveDocument.getObject('SquareTubeZAxis').Visibility = False\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Framework Assembly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 129,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Link***XAxis, Link***YAxis and Link***ZAxis\n",
    "\n",
    "if App.ActiveDocument.getObject('Framework'):\n",
    "    App.ActiveDocument.getObject('Framework').removeObjectsFromDocument()\n",
    "    App.ActiveDocument.removeObject('Framework')\n",
    "    App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.addObject('App::Part', 'Framework')\n",
    "Gui.ActiveDocument.ActiveView.setActiveObject('part', App.ActiveDocument.getObject('Framework'))\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "\n",
    "# Link***XAxis\n",
    "\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link001XAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link002XAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link003XAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link004XAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link005XAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link006XAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link007XAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link008XAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link009XAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link010XAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link011XAxis')\n",
    "\n",
    "App.ActiveDocument.getObject('Link001XAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeXAxis')\n",
    "App.ActiveDocument.getObject('Link002XAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeXAxis')\n",
    "App.ActiveDocument.getObject('Link003XAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeXAxis')\n",
    "App.ActiveDocument.getObject('Link004XAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeXAxis')\n",
    "App.ActiveDocument.getObject('Link005XAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeXAxis')\n",
    "App.ActiveDocument.getObject('Link006XAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeXAxis')\n",
    "App.ActiveDocument.getObject('Link007XAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeXAxis')\n",
    "App.ActiveDocument.getObject('Link008XAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeXAxis')\n",
    "App.ActiveDocument.getObject('Link009XAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeXAxis')\n",
    "App.ActiveDocument.getObject('Link010XAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeXAxis')\n",
    "App.ActiveDocument.getObject('Link011XAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeXAxis')\n",
    "\n",
    "App.ActiveDocument.getObject('Link002XAxis').setExpression('.Placement.Base.y', u'-SquareTubeYAxis.Shape.BoundBox.YLength/2 - 40/2')\n",
    "App.ActiveDocument.getObject('Link003XAxis').setExpression('.Placement.Base.y', u'SquareTubeYAxis.Shape.BoundBox.YLength/2 + 40/2')\n",
    "App.ActiveDocument.getObject('Link004XAxis').setExpression('.Placement.Base.y', u'-SquareTubeYAxis.Shape.BoundBox.YLength/4 - 40/2')\n",
    "App.ActiveDocument.getObject('Link005XAxis').setExpression('.Placement.Base.y', u'SquareTubeYAxis.Shape.BoundBox.YLength/4 - 40/2')\n",
    "\n",
    "App.ActiveDocument.getObject('Link006XAxis').setExpression('.Placement.Base.z', u'Pad003.Length.Value + 40')\n",
    "App.ActiveDocument.getObject('Link007XAxis').setExpression('.Placement.Base.z', u'Pad003.Length.Value + 40')\n",
    "App.ActiveDocument.getObject('Link007XAxis').setExpression('.Placement.Base.y', u'-SquareTubeYAxis.Shape.BoundBox.YLength/2 - 40/2')\n",
    "App.ActiveDocument.getObject('Link008XAxis').setExpression('.Placement.Base.z', u'Pad003.Length.Value + 40')\n",
    "App.ActiveDocument.getObject('Link008XAxis').setExpression('.Placement.Base.y', u'SquareTubeYAxis.Shape.BoundBox.YLength/2 + 40/2')\n",
    "\n",
    "App.ActiveDocument.getObject('Link009XAxis').setExpression('.Placement.Base.z', u'-Pad006.Length.Value - 40')\n",
    "App.ActiveDocument.getObject('Link010XAxis').setExpression('.Placement.Base.z', u'-Pad006.Length.Value - 40')\n",
    "App.ActiveDocument.getObject('Link010XAxis').setExpression('.Placement.Base.y', u'-SquareTubeYAxis.Shape.BoundBox.YLength/2 - 40/2')\n",
    "App.ActiveDocument.getObject('Link011XAxis').setExpression('.Placement.Base.z', u'-Pad006.Length.Value - 40')\n",
    "App.ActiveDocument.getObject('Link011XAxis').setExpression('.Placement.Base.y', u'SquareTubeYAxis.Shape.BoundBox.YLength/2 + 40/2')\n",
    "\n",
    "\n",
    "# Link***YAxis\n",
    "\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link001YAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link002YAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link003YAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link004YAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link005YAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link006YAxis')\n",
    "\n",
    "App.ActiveDocument.getObject('Link001YAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeYAxis')\n",
    "App.ActiveDocument.getObject('Link002YAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeYAxis')\n",
    "App.ActiveDocument.getObject('Link003YAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeYAxis')\n",
    "App.ActiveDocument.getObject('Link004YAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeYAxis')\n",
    "App.ActiveDocument.getObject('Link005YAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeYAxis')\n",
    "App.ActiveDocument.getObject('Link006YAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeYAxis')\n",
    "\n",
    "App.ActiveDocument.getObject('Link001YAxis').setExpression('.Placement.Base.x', u'SquareTubeXAxis.Shape.BoundBox.XLength/2 + 40/2')\n",
    "App.ActiveDocument.getObject('Link002YAxis').setExpression('.Placement.Base.x', u'-SquareTubeXAxis.Shape.BoundBox.XLength/2 - 40/2')\n",
    "\n",
    "App.ActiveDocument.getObject('Link003YAxis').setExpression('.Placement.Base.z', u'Pad003.Length.Value + 40')\n",
    "App.ActiveDocument.getObject('Link003YAxis').setExpression('.Placement.Base.x', u'SquareTubeXAxis.Shape.BoundBox.XLength/2 + 40/2')\n",
    "App.ActiveDocument.getObject('Link004YAxis').setExpression('.Placement.Base.z', u'Pad003.Length.Value + 40')\n",
    "App.ActiveDocument.getObject('Link004YAxis').setExpression('.Placement.Base.x', u'-SquareTubeXAxis.Shape.BoundBox.XLength/2 - 40/2')\n",
    "\n",
    "App.ActiveDocument.getObject('Link005YAxis').setExpression('.Placement.Base.z', u'-Pad006.Length.Value - 40')\n",
    "App.ActiveDocument.getObject('Link005YAxis').setExpression('.Placement.Base.x', u'SquareTubeXAxis.Shape.BoundBox.XLength/2 + 40/2')\n",
    "App.ActiveDocument.getObject('Link006YAxis').setExpression('.Placement.Base.z', u'-Pad006.Length.Value - 40')\n",
    "App.ActiveDocument.getObject('Link006YAxis').setExpression('.Placement.Base.x', u'-SquareTubeXAxis.Shape.BoundBox.XLength/2 - 40/2')\n",
    "\n",
    "\n",
    "# Link***ZAxis\n",
    "\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link001ZAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link002ZAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link003ZAxis')\n",
    "App.ActiveDocument.getObject('Framework').newObject('App::Link', 'Link004ZAxis')\n",
    "\n",
    "App.ActiveDocument.getObject('Link001ZAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeZAxis')\n",
    "App.ActiveDocument.getObject('Link002ZAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeZAxis')\n",
    "App.ActiveDocument.getObject('Link003ZAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeZAxis')\n",
    "App.ActiveDocument.getObject('Link004ZAxis').LinkedObject = App.ActiveDocument.getObject('SquareTubeZAxis')\n",
    "\n",
    "App.ActiveDocument.getObject('Link001ZAxis').setExpression('.Placement.Base.x', u'SquareTubeXAxis.Shape.BoundBox.XLength/2 + 40/2')\n",
    "App.ActiveDocument.getObject('Link001ZAxis').setExpression('.Placement.Base.y', u'SquareTubeYAxis.Shape.BoundBox.YLength/2 + 40/2')\n",
    "App.ActiveDocument.getObject('Link001ZAxis').setExpression('.Placement.Base.z', u'Pad003.Shape.BoundBox.ZLength/2 + 40/2')\n",
    "\n",
    "App.ActiveDocument.getObject('Link002ZAxis').setExpression('.Placement.Base.x', u'SquareTubeXAxis.Shape.BoundBox.XLength/2 + 40/2')\n",
    "App.ActiveDocument.getObject('Link002ZAxis').setExpression('.Placement.Base.y', u'-SquareTubeYAxis.Shape.BoundBox.YLength/2 - 40/2')\n",
    "App.ActiveDocument.getObject('Link002ZAxis').setExpression('.Placement.Base.z', u'Pad003.Shape.BoundBox.ZLength/2 + 40/2')\n",
    "\n",
    "App.ActiveDocument.getObject('Link003ZAxis').setExpression('.Placement.Base.x', u'-SquareTubeXAxis.Shape.BoundBox.XLength/2 - 40/2')\n",
    "App.ActiveDocument.getObject('Link003ZAxis').setExpression('.Placement.Base.y', u'SquareTubeYAxis.Shape.BoundBox.YLength/2 + 40/2')\n",
    "App.ActiveDocument.getObject('Link003ZAxis').setExpression('.Placement.Base.z', u'Pad003.Shape.BoundBox.ZLength/2 + 40/2')\n",
    "\n",
    "App.ActiveDocument.getObject('Link004ZAxis').setExpression('.Placement.Base.x', u'-SquareTubeXAxis.Shape.BoundBox.XLength/2 - 40/2')\n",
    "App.ActiveDocument.getObject('Link004ZAxis').setExpression('.Placement.Base.y', u'-SquareTubeYAxis.Shape.BoundBox.YLength/2 - 40/2')\n",
    "App.ActiveDocument.getObject('Link004ZAxis').setExpression('.Placement.Base.z', u'Pad003.Shape.BoundBox.ZLength/2 + 40/2')\n",
    "\n",
    "\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "Gui.ActiveDocument.ActiveView.setActiveObject('part', None)\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 130,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Save\n",
    "\n",
    "Gui.ActiveDocument.ActiveView.setActiveObject('pdbody', None)\n",
    "Gui.ActiveDocument.ActiveView.setActiveObject('part', None)\n",
    "\n",
    "Gui.ActiveDocument.ActiveView.viewDefaultOrientation()\n",
    "Gui.ActiveDocument.ActiveView.setCameraType(\"Perspective\")\n",
    "Gui.SendMsgToActiveView(\"ViewFit\")\n",
    "\n",
    "App.ActiveDocument.recompute()\n",
    "\n",
    "App.ActiveDocument.saveAs(\"./Framework/Framework.FCStd\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "FreeCAD",
   "language": "",
   "name": "freecad"
  },
  "language_info": {
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
